CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE EMPLOYEE(EMP_ID INT PRIMARY KEY AUTO_INCREMENT,EMP_NAME VARCHAR(50), SALARY INT, AGE INT, DATE_OF_JOINING DATE);
SELECT * FROM EMPLOYEE;
INSERT INTO EMPLOYEE(EMP_NAME,SALARY,AGE,DATE_OF_JOINING) VALUES("Gayathri",500000,22,"2023-09-12");
SELECT * FROM EMPLOYEE;
DELETE FROM EMPLOYEE WHERE EMP_ID =2;
INSERT INTO EMPLOYEE(EMP_NAME,SALARY,AGE,DATE_OF_JOINING)  VALUES("Sneha",40000,23,"2024-12-23"),("Grace",300000,21,"2025-09-12");
SELECT * FROM EMPLOYEE;
SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE EMP_NAME LIKE "G%";
SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE EMP_NAME LIKE "%y%";
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '_e';
SELECT EMP_NAME, AGE FROM EMPLOYEE ORDER BY EMP_NAME DESC;
DESC EMPLOYEE;
SELECT EMP_NAME, AGE FROM EMPLOYEE WHERE AGE IN (20,21);
SELECT EMP_NAME,AGE,DATE_OF_JOINING FROM EMPLOYEE WHERE DATE_OF_JOINING BETWEEN "2024-01-01" AND "2025-12-31";
SELECT * FROM EMPLOYEE;
SELECT EMP_ID AS EID FROM EMPLOYEE;
SELECT * FROM EMPLOYEE;
SELECT E.EMP_ID  FROM EMPLOYEE AS E;
CREATE TABLE BANK_DETAILS(ACCOUNT_NO INT PRIMARY KEY, EMP_ID INT, BANK_NAME VARCHAR(50));
INSERT INTO BANK_DETAILS VALUES(123456789,1,"HDFC Bank"),(234567890,4,"ICIC Bank");
SELECT * FROM BANK_DETAILS;
SELECT E.EMP_NAME,B.ACCOUNT_NO
FROM EMPLOYEE AS E
INNER JOIN BANK_DETAILS AS B
ON E.EMP_ID = B.EMP_ID;
SELECT E.EMP_NAME, B.ACCOUNT_NO
FROM EMPLOYEE AS E
LEFT JOIN BANK_DETAILS AS B
ON E.EMP_ID = B.EMP_ID;
SELECT E.EMP_NAME, B.ACCOUNT_NO
FROM EMPLOYEE AS E
RIGHT JOIN BANK_DETAILS AS B
ON E.EMP_ID = B.EMP_ID;
SELECT E.EMP_NAME,B.ACCOUNT_NO
FROM EMPLOYEE AS E
LEFT JOIN BANK_DETAILS AS B
ON E.EMP_ID = B.EMP_ID
UNION 
SELECT E.EMP_NAME,B.ACCOUNT_NO
FROM EMPLOYEE AS E
RIGHT JOIN BANK_DETAILS AS B
ON E.EMP_ID=B.EMP_ID;
SELECT * FROM BANK_DETAILS;
INSERT INTO BANK_DETAILS VALUES(12389708,5,"HDFC Bank");
SELECT * FROM BANK_DETAILS;
